### ISSUE TITLE
Part of speech and gender is sometimes in the definition and sometimes in the definition tags

### ISSUE THREAD

**Issue by anewstheart** [seth-js/yomichan-sr-hr#2]
```
    [
        "brat",
        "",
        "non-lemma",
        "",
        0,
        [
            "noun -automated- {brat -> brat} nominative singular (->brat)"
        ],
        0,
        ""
    ],
    [
        "srodan",
        "/srôdan/",
        "adj",
        "",
        0,
        [
            "akin, kindred",
            "cognate, related",
            "allied to, analogous",
            "congenial"
        ],
        0,
        ""
    ],
    [
        "уништивост",
        "/unǐʃtiʋoːst/",
        "noun feminine",
        "",
        0,
        [
            "(uncountable) destructibility"
        ],
        0,
        ""
    ],
```

**Comment by anewstheart** [comment]
I see that you explained how the tags and definition are structured here:

https://github.com/seth-js/yomichan-ru/issues/1#issuecomment-1412756672

I will have to read it more carefully and see if I can adapt something for jiroujisho tomorrow.

**Comment by seth-js** [comment]
Yeah, this has to do with how my custom Yomichan handles these special `non-lemma` entries. For example, the non-lemma "brat" entry will look for another entry called "brat" with the `noun` POS. Once it finds it, it places "nominative singular" in the hidden inflection info box as a definition. Then it hides the `non-lemma` entry.

**Comment by anewstheart** [comment]
After further inspection I see that:

- For a non-lemma word, the {expression} value is replaced by the lemma.
- The {expression} is what is added to Anki for memorization.

I prefer to learn the inflected forms of words rather than the lemma because that is what is encountered in real life.

For my purposes, for non-lemma words, I will:

- Move the PoS from the definition to the tags string.
- Remove the -automated- string from the definition.
- Remove the  {xxx-> xxx} inflection lemma bracket from the definition.

```

I understand that I will not have complete lemmatization of rare multi-level lemma references. But, that is a minor issue and jiroujisho supports recursive lookup of dictionary entries by selecting the lemma from the definition.

    [
        "priznali",
        "",
        "non-lemma",
        "",
        0,
        [
            "verb -automated- {priznali -> priznati} masculine plural active past participle of priznati (->priznati)"
        ],
        0,
        ""
    ]
```

Becomes:

```

    [
        "priznali",
        "",
        "verb",
        "",
        0,
        [
            "masculine plural active past participle of priznati (->priznati)"
        ],
        0,
        ""
    ]

```
