### ISSUE TITLE
Split term banks into ~10,000 term files for easier handling

### ISSUE THREAD

**Issue by anewstheart** [seth-js/yomichan-sr-hr#3]
It would be handy if the term bank files were smaller so that they can be investigated and manipulated without special memory handling.

Pyglossary outputs 10,000 terms per bank by default:

https://github.com/ilius/pyglossary/blob/master/doc/p/yomichan.md

**Comment by seth-js** [comment]
I'll try to get this done tomorrow.

**Comment by seth-js** [comment]
The dictionary now has the term bank as smaller files with 10,000 entries each.

https://github.com/seth-js/yomichan-sr-hr/releases/tag/rel-6-2-23
