### ISSUE TITLE
Script for converting Wiktionary data to Yomichan dictionary file

### ISSUE THREAD

**Issue by CrAZONE0** [seth-js/yomichan-sr-hr#5]
Sorry for asking here, but didn't know where else to do. How do you convert Wiktionary data (not only for Serbo-Croatian) to Yomichan dictionaries? Could you share your script?

**Comment by seth-js** [comment]
I added the code to the repository. There may be some comments in the code I forgot to remove.

**Comment by parfait8566** [comment]
> I added the code to the repository. There may be some comments in the code I forgot to remove.

Thanks! Could you add the code for the other languages as well?

**Comment by seth-js** [comment]
@parfait8566 
Added the code for [Spanish](https://github.com/seth-js/yomichan-es). That one was probably the most straightforward to work with. It also includes code for parsing a corpus and creating a frequency list.

**Comment by parfait8566** [comment]
> @parfait8566 Added the code for [Spanish](https://github.com/seth-js/yomichan-es). That one was probably the most straightforward to work with. It also includes code for parsing a corpus and creating a frequency list.

Thanks. I tried to make the scripts work for Latin and Ancient Greek but doesn't seem to work very well.

**Comment by parfait8566** [comment]
How did you find about all the tags (cases, numbers, modifiers, tenses, verbForms, misc, etc.)?

**Comment by seth-js** [comment]
>How did you find about all the tags (cases, numbers, modifiers, tenses, verbForms, misc, etc.)?

Each language requires some experimentation. I manually check through each tag to make sure I'm getting all the necessary information I want.

The `formStuff` array contains all inflections that have their own page on Wiktionary. These are the highest quality ones usually without mistakes.

The `automatedForms` object handles data from the `forms` array. This is the one most prone to bugs and incorrect data. You need to look through them and make sure to filter out garbage data by using the `blacklistedTags` array.

**Comment by parfait8566** [comment]
> Each language requires some experimentation. I manually check through each tag to make sure I'm getting all the necessary information I want.

How do you check? I can't find any page on Wiktionary containing all the tags.

**Comment by seth-js** [comment]
Try something like this:

```javascript
const uniqueTags = {};

for (const tag of tags) {
  if (!uniqueTags[tag]) {
    uniqueTags[tag] = 1;
    console.log(tag);
  }
}
```

Or like this:
```javascript
const uniqueTags = [];

for (const tag of tags) {
  if (!uniqueTags.includes(tag)) {
    uniqueTags.push(tag)
    console.log(tag);
  }
}
```

**Comment by parfait8566** [comment]
I'm sorry for annoying you but I'm not familiar with code that much, where should I do write this code?

**Comment by seth-js** [comment]
I would recommend using `yomichan-es`'s code as a base. I've just updated it with all the newest changes I was experimenting with, but wasn't ready to release yet.

Open `tidy-up.js`, and below:

```javascript
const blacklistedTags = [
  'table-tags',
  'nominative',
  'canonical',
  'class',
  'error-unknown-tag',
  'error-unrecognized-form',
  'infinitive',
];
```

Add:

```javascript
const uniqueTags = [];
```

Then, underneath:

```javascript
if (forms) {
      for (const { form, tags } of forms) {
        if (form && tags && !tags.some(value => blacklistedTags.includes(value))) {
```

Add:

```javascript
for (const tag of tags) {
  if (!uniqueTags.includes(tag)) {
    uniqueTags.push(tag);
    console.log(tag);
  }
}
```
